import express from "express";
import { registerUser, LoginUser, Forgotpassword, VerifyOtp, ResetPassword } from "../controllers/auth.controllers.js";
import authMiddleware from "../middlewares/auth.middleware.js";
const authrouter = express.Router();
    authrouter.post("/register", registerUser);
    authrouter.post("/login", LoginUser);
    authrouter.post("/forgot-password", Forgotpassword);
    authrouter.post("/verify-otp", VerifyOtp);
    authrouter.post("/reset-password", ResetPassword);
export default authrouter;
